# Generated by Django 4.2.17 on 2024-12-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_posted_at_alter_job_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location_type',
            field=models.CharField(choices=[('Remote', 'Remote'), ('On-Site', 'On-Site'), ('Hybrid', 'Hybrid'), ('Remote, On-Site', 'Remote, On-Site'), ('Remote, Hybrid', 'Remote, Hybrid'), ('On-Site, Hybrid', 'On-Site, Hybrid')], max_length=50),
        ),
    ]
